### PR TITLE
Slides from JuMP-dev 2019

### LINKED ISSUE #117: Slides from the third workshop not available
Unlike the two first workshops, the slides are not yet available for the third one. Do you have an ETA :)?

### PR DESCRIPTION
**Pull request by joehuchette**
I don't have slides from:
- [x] @mlubin 
- [x] @StefanKarpinski
- [ ] @chriscoey
- [x] @jd-lara
- [x] @blegat
- [ ] Tillmann Weisser
- [ ] @mforets

If you're on this list, could you please share slides with me (or contact me, here or via email, if you don't wish to share them)?

Closes #117

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Here you go: [Stefan's slides](https://github.com/JuliaOpt/juliaopt.github.io/files/3015897/2019.JuMP-dev.talk.pdf).

**Comment by mlubin** [comment]
I emailed my slides to @joehuchette.

**Comment by StefanKarpinski** [comment]
I posted my slides here in this issue.

**Comment by joehuchette** [comment]
cc @mforets, who I had omitted from the initial list.

**Comment by joehuchette** [comment]
Merging what I have at currently, will open separate PRs with the remaining ones.

**Pull request merged**
