### PR TITLE
Add CDD in solvers table

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by chkwon** [comment]
@blegat Thanks for PR. I was wondering if CDD can be used via MathProgBase.jl. If not, I believe http://www.juliaopt.org/packages/ is a better place to put.

**Comment by blegat** [comment]
Yes, in a similar way that `CSDP` can be used as a `ConicModel` via the `SDtoConic` bridge of [SemidefiniteModels.jl](https://github.com/JuliaOpt/SemidefiniteModels.jl), `CDD` can be used as a `LinearQuadraticModel` via the `PolyhedratoLPQP` bridge of [Polyhedra.jl](https://github.com/JuliaPolyhedra/Polyhedra.jl).

**Comment by chkwon** [comment]
Just to confirm: As far as I understand, all solvers listed in the solver table can be used in the following form:

    m = Model(solver=ECOSSolver())

Can `CDD` and `CSDP` be used in a similar way? 

Another issue: all solvers listed in the table are by JuliaOpt. Any policy? @mlubin Do we want to list non-JuliaOpt solvers here? Like Pajarito?

**Comment by blegat** [comment]
Yes, they can be used that way :)

**Comment by mlubin** [comment]
No objection to listing solver wrappers which aren't hosted under JuliaOpt. Pajarito is not quite ready for the attention yet, though.

**Comment by chkwon** [comment]
@blegat Thanks for the confirmation! By the way, I failed to test:

```
julia> Pkg.status("Polyhedra")
 - Polyhedra                     0.1.2

julia> Pkg.status("CDDLib")
 - CDDLib                        0.1.1

julia> m = Model(solver=CDDSolver())
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver is CDD

julia> @variable(m, 0 <= x <= 2 )
x

julia> @variable(m, 0 <= y <= 30 )
y

julia> @objective(m, Max, 5x + 3*y )
5 x + 3 y

julia> @constraint(m, 1x + 5y <= 3.0 )
x + 5 y ≤ 3

julia> print(m)
Max 5 x + 3 y
Subject to
 x + 5 y ≤ 3
 0 ≤ x ≤ 2
 0 ≤ y ≤ 30

julia> status = solve(m)
ERROR: MethodError: no method matching Polyhedra.PolyhedraToLPQPBridge(::CDDLib.CDDPolyhedraModel, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::Array{Int64,1}, ::Array{Array{Int64,1},1})
Closest candidates are:
  Polyhedra.PolyhedraToLPQPBridge(::Polyhedra.AbstractPolyhedraModel, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol) at /Users/chkwon/.julia/v0.5/Polyhedra/src/polyhedra_to_lpqp.jl:7
  Polyhedra.PolyhedraToLPQPBridge(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /Users/chkwon/.julia/v0.5/Polyhedra/src/polyhedra_to_lpqp.jl:7
  Polyhedra.PolyhedraToLPQPBridge(::Polyhedra.AbstractPolyhedraModel) at /Users/chkwon/.julia/v0.5/Polyhedra/src/polyhedra_to_lpqp.jl:17
  ...
 in Polyhedra.PolyhedraToLPQPBridge(::CDDLib.CDDPolyhedraModel) at /Users/chkwon/.julia/v0.5/Polyhedra/src/polyhedra_to_lpqp.jl:17
 in LinearQuadraticModel(::CDDLib.CDDSolver) at /Users/chkwon/.julia/v0.5/CDDLib/src/mathprogbase.jl:33
 in #build#93(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /Users/chkwon/.julia/v0.5/JuMP/src/solvers.jl:370
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
 in #solve#88(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /Users/chkwon/.julia/v0.5/JuMP/src/solvers.jl:134
 in solve(::JuMP.Model) at /Users/chkwon/.julia/v0.5/JuMP/src/solvers.jl:116
```

**Comment by blegat** [comment]
Oops, I'll tell you when this is fixed, thanks for noticing this.

**Comment by blegat** [comment]
@chkwon The CDD solver should work now with CDDLib v0.1.2 :)

**Comment by chkwon** [comment]
@blegat Great! Could you make the new working version updated in METADATA.jl?

**Comment by blegat** [comment]
Done :)

**Comment by chkwon** [comment]
@blegat Thanks!!! If you can write an example using CDDSolver() somewhere, it will be good. I think users at least know

```
m = Model(solver=CDDSolver())
```

It may be confusing between `CDDLibSolver()` and `CDDSolver()`.

**Comment by blegat** [comment]
@chkwon done : https://github.com/JuliaPolyhedra/CDDLib.jl/commit/d5bd625b8cddb12ba633c5730b1b162f11a1aaed :)

**Comment by chkwon** [comment]
Thanks!

**Pull request merged**
