### PR TITLE
jump.dev redirects for MathOptInterface docs

### PR DESCRIPTION
**Pull request by mlubin**
The directory and link structure are copied over from the `gh-pages` branch of MathOptInterface. All .html files are replaced with redirects. All other files like js are copied without change (not sure if this is needed, but seems to be safe).

I have a script to generate these PRs for any repos with docs that we want to move from JuliaOpt to JuMP-dev.

### CODE REVIEW

**Comment by blegat** [comment]
Shouldn't this be merged into `gh-pages` so that the juliaopt server is updates one last time and then we move the repo to the JuMP-dev org ?

**Comment by mlubin** [comment]
Hmm, I've been assuming that when the repository is transferred, https://juliaopt.org/MathOptInterface.jl will disappear, so these files will replace that. Maybe the stale files would be left instead, I'm not sure.

**Comment by mlubin** [comment]
I tested this out and it seems to work as I expected.
I created juliaopt/migration-test, moved it to the jump-dev org. The github pages for migration-test disappeared from juliaopt.org after the move. I then pushed a replacement page to juliaopt.org:
https://jump.dev/migration-test/
https://www.juliaopt.org/migration-test/

**Comment by blegat** [comment]
Looks good then, let's do it.

**Pull request merged**
