### PR TITLE
Add PolyJuMP and SumOfSquares in packages list

### PR DESCRIPTION
**Pull request by blegat**
CC @joehuchette @chriscoey @rdeits @ameliaperry : do the descriptions look good for you ?

### CODE REVIEW

**Comment by rdeits** [comment]
looks good to me!

**Comment by chriscoey** [comment]
Moi aussi.

At some point we may want to clarify that we are talking about the type of polynomial optimization where the variables aren't the `x` in `p(x)`, but rather the coefficients of `p(x)` itself. This distinction sometimes trips me up _still_, as I am separately working on polynomial (specifically signomial+GP) problems where the variables are the `x`s. I'm not sure how to word this clarification though.

**Comment by blegat** [comment]
@chriscoey one way to clarify this is, instead of using the vague terminology "[JuMP extension] for polynomial optimization", we say "[JuMP extension] for polynomial variables".
Indeed, we can really see this as adding one variable type: the polynomials.
The fact that we allow parametrizing the coefficient is just syntactic sugar.
For instance, the program
```
min_a a
x^2 + axy + y^2 >= 0 for all x, y
```
can be reformulated as
```
min_a
E_(mu_1)[p(x)] = 1
E_(mu_2)[p(x)] = a
E_(mu_3)[p(x)] = 1
p(x) >= 0
```
where
* `mu_1` is the distribution with all moments equals to zero except `E_(mu_1)[x^2] = 1`
* `mu_2` is the distribution with all moments equals to zero except `E_(mu_2)[xy] = 1`
* `mu_3` is the distribution with all moments equals to zero except `E_(mu_3)[y^2] = 1`

In the reformulation, we are handling expectations and polynomials as first class citizens and we never actually need to write down the polynomial in any basis.
So I think the cleaner way to say what `PolyJuMP` does is adding polynomials and expectations as possible variable types. The fact that we specify the polynomials by their coefficients and the expectations by their moments is really just a technical detail.

So what do you all say ? Do we replace the description with "[JuMP extension] for polynomial variables" ? Or do we even say "[JuMP extension] for polynomial and expectation variables" or do we just keep "[JuMP extension] for polynomial optimization" ?

**Comment by chriscoey** [comment]
If you make clear at the start of the documentation that this extension gives support for creating polynomial (and expectation) variables, where the optimization variables are coefficients rather than the `x` or `y` in the `p(x,y)`, then people will hopefully understand. We aren't solving problems like `min_x p(x)`, which is also called polynomial optimization (possibly nonconvex) in literature, rather we are solving problems like the example you give above where `a` is a coefficient.

**Comment by joehuchette** [comment]
I think the description on the website is fine, any clarification can go in the README for PolyJuMP.

**Pull request merged**
